from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from  . import views
from . import chat
urlpatterns = [
    path('save-image/', views.SaveImageAPIView.as_view(), name='save_image'),
    path('save-categories/', views.SaveCategoryAPIView.as_view(), name='save_categories'),
    path('save-subcategories/', views.SaveSubCategoryAPIView.as_view(), name='save_subcategories'),
    path('edit-categories/', views.EditCategoryAPIView.as_view(), name='edit_categories'),
    path('edit-subcategories/', views.EditSubCategoryAPIView.as_view(), name='edit_subcategories'),
    path('delete-categories/', views.DeleteCategoryAPIView.as_view(), name='delete_categories'),
    path('update-category-order/', views.UpdateCategoryOrderAPIView.as_view(), name='update_category_order'),
    path('delete-subcategories/', views.DeleteSubCategoryAPIView.as_view(), name='delete_subcategories'),
    path('show-categories/', views.ShowCategoryAPIView.as_view(), name='show_categories'),
    path('show-subcategories/', views.ShowSubCategoryAPIView.as_view(), name='show_subcategories'),
    path('update-subcategory-order/', views.UpdateSubCategoryOrderAPIView.as_view(), name='update_subcategory_order'),
    path('update_hidden_status/', views.UpdateHiddenStatusAPIView.as_view(), name='update_hidden_status'),
    path('generate-product-id/', views.GenerateProductIdAPIView.as_view(), name='generate_product_id'),
    path("show-product/", views.ShowProductsAPIView.as_view(), name='show-product'),
    path("delete-product/", views.DeleteProductAPIView.as_view(), name='delete-product'),
    path("save-product/", views.SaveProductAPIView.as_view(), name='save-product'),
    path('show_specific_product/', views.ShowSpecificProductAPIView.as_view(), name="show_specific_product"),
    path('show_product_seo/', views.ShowProductSEOAPIView.as_view(), name='show_product_seo'),
    path('show_product_variant/', views.ShowProductVariantAPIView.as_view(), name="show_product_variant"),
    path('show_product_shipping_info/', views.ShowProductShippingInfoAPIView.as_view(), name="show_product_shipping_info"),
    path('show_product_other_details/', views.ShowProductOtherDetailsAPIView.as_view(), name="show_product_other_details"),
    path('show_product_variants/', views.ShowVariantCombinationsAPIView.as_view(), name="show_product_variants"),
    path('edit-product/', views.EditProductAPIView.as_view(), name="edit_product"),
    path("update-product-order/", views.UpdateProductOrderAPIView.as_view(), name="update-product-order"),
    path('show_product_attributes/', views.ShowProductAttributesAPIView.as_view(), name='show_product_attributes'),
    path('show_nav_items/', views.ShowNavItemsAPIView.as_view(), name='show_nav_items'),
    path('show-user/', views.ShowUserAPIView.as_view(), name='show_users'),
    path('save-user/', views.SaveUserAPIView.as_view(), name='save_user'),
    path('show-cart/', views.ShowCartAPIView.as_view(), name='show_cart'),
    path('save-cart/', views.SaveCartAPIView.as_view(), name='save_cart'),
    path('delete-cart-item/', views.DeleteCartItemAPIView.as_view(), name='delete_cart_item'),
    path('show-order/', views.ShowOrderAPIView.as_view(), name='show_order'),
    path('save-order/', views.SaveOrderAPIView.as_view(), name='save_order'),
    path('edit-order/', views.EditOrderAPIView.as_view(), name='edit_order'),
    path('save-admin/', views.SaveAdminAPIView.as_view(), name='save_admin'),
    path('show-admin/', views.ShowAdminAPIView.as_view(), name='show_admin'),
    path('delete-admin/', views.DeleteAdminAPIView.as_view(), name='delete_admin'),
    path('admin-login/', views.AdminLoginAPIView.as_view(), name='admin_login'),
    path('show-all-images/', views.ShowAllImagesAPIView.as_view(), name='show_all_images'),
    path('edit-image/', views.EditImageAPIView.as_view(), name='edit_image'),
    path('delete-image/', views.DeleteImageAPIView.as_view(), name='delete_image'),
    path('first-carousel/', views.FirstCarouselAPIView.as_view(), name='first_carousel'),
    path('second-carousel/', views.SecondCarouselAPIView.as_view(), name='second_carousel'),
    path('hero-banner/', views.HeroBannerAPIView.as_view(), name='hero_banner'),
    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notification-update', views.update_notification_status, name='update_notifications'),
    path('update-image/<str:image_id>/', views.update_image, name='update_image'),
    path("save-blog/", views.save_blog, name="save_blog"),
    path("show-blogs/", views.show_blogs, name="show_blogs"),
    path("edit-blog/<str:blog_id>/", views.edit_blog, name="edit_blog"),
    path("user-response/", chat.UserResponseAPIView.as_view(), name="user_response"),
    path("bot-response/", chat.BotResponseAPIView.as_view(), name="bot_response"),
    path("bot-prompts/", chat.BotPromptsAPIView.as_view(), name="bot_prompts"),
]

