
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
import os
from datetime import timedelta
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# ---------------------------
# Load environment variables
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Try multiple likely .env locations
ENV_CANDIDATES = [
    BASE_DIR / ".env",                              # e.g., Back_End/.env
    BASE_DIR / "admin_backend_final" / ".env",      # your current location
]

for env_path in ENV_CANDIDATES:
    if env_path.exists():
        load_dotenv(env_path, override=False)

# ---------------------------
# Helpers
# ---------------------------
def env_bool(name: str, default: bool = False) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.lower() in ("1", "true", "yes", "on")

# ---------------------------
# Security / Core
# ---------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key")
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "app.click2print.store",
    "app.crm.click2print.store",  # CRM admin panel
    "api.click2print.store",
    "click2print.store",
] + [h.strip() for h in os.getenv("ALLOWED_HOSTS_EXTRA", "").split(",") if h.strip()]

APPEND_SLASH = True

# ---------------------------
# Applications
# ---------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",

    # Local
    "admin_backend_final.apps.AdminBackendFinalConfig",
]

# ---------------------------
# Middleware
# ---------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # keep on top for CORS
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # compress API responses
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # keep enabled for HTML views
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# ---------------------------
# Database (MySQL via env, fallback to SQLite)
# ---------------------------
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")

# Use MySQL if all credentials are provided, otherwise fallback to SQLite
if DB_NAME and DB_USER and DB_PASSWORD and DB_HOST:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": DB_HOST,
            "PORT": str(os.getenv("DB_PORT", "3306")),  # ensure string
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        }
    }
else:
    # Fallback to SQLite for development/testing
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ---------------------------
# Password validation
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------
# I18N
# ---------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# ---------------------------
# Static & Media
# ---------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", str(BASE_DIR / "static"))

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", str(BASE_DIR / "media"))

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------
# CORS / CSRF
# ---------------------------
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", True)

if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "https://app.click2print.store",
        "https://app.crm.click2print.store",  # CRM admin panel
        "https://api.click2print.store",
        "https://click2print.store",
        "https://www.click2print.store",
    ] + [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS_EXTRA", "").split(",") if o.strip()]

CORS_ALLOW_CREDENTIALS = True

# Allow all HTTP methods for CORS (including OPTIONS for preflight)
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow only header NAMES here (lowercase). Do NOT include secret values.
FRONTEND_HEADER_NAME = os.getenv("FRONTEND_HEADER_NAME", "x-frontend-key").lower()
CORS_ALLOW_HEADERS = list(default_headers) + [
    FRONTEND_HEADER_NAME,  # e.g., "x-frontend-key"
    "x-device-uuid",
    "x-csrftoken",
]

# Cache preflight responses for 1 hour
CORS_PREFLIGHT_MAX_AGE = 3600

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
    "https://app.click2print.store",
    "https://app.crm.click2print.store",  # CRM admin panel
    "https://api.click2print.store",
    "https://click2print.store",
    "https://www.click2print.store",
] + [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS_EXTRA", "").split(",") if o.strip()]

# ---------------------------
# Forwarded/Proxy & HTTPS
# ---------------------------
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)

SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
# CSRF cookie settings for local development (different ports)
# Note: For cross-origin (different ports), SameSite=Lax allows cookies for top-level navigations
# but not for fetch requests. We use X-CSRFToken header + cookie double-submit pattern.
CSRF_COOKIE_SAMESITE = "Lax"  # Allows cookies for same-site requests
CSRF_COOKIE_HTTPONLY = False  # Must be False to allow reading for X-CSRFToken header (double-submit pattern)
CSRF_COOKIE_PATH = "/"  # Cookie available for all paths

# ---------------------------
# Custom User
# ---------------------------
AUTH_USER_MODEL = "admin_backend_final.User"

# ---------------------------
# DRF & JWT
# ---------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # APIs
        "rest_framework.authentication.SessionAuthentication",         # Browsable API/admin
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("JWT_ACCESS_MINUTES", "10"))),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "user_id",  # Use user_id instead of id for custom User model
    "USER_ID_CLAIM": "user_id",
}

# ---------------------------
# File uploads
# ---------------------------
FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(1024 * 1024 * 1024)))  # 1GB
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(1024 * 1024 * 1024)))  # 1GB

# ---------------------------
# Misc envs
# ---------------------------
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
DATA_API_BASE = os.getenv("DATA_API_BASE", "http://127.0.0.1:8000/api")
BOT_DEFAULT_LANG = os.getenv("BOT_DEFAULT_LANG", "en")

# ---------------------------
# Email Configuration (SMTP)
# ---------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'maffanilahi@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'iwxmahwpkqzvdizl')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
SERVER_EMAIL = DEFAULT_FROM_EMAIL  # For error reporting

# ---------------------------
# Production toggles (optional)
# ---------------------------
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
