from django.urls import path
from .views import (
    attendance_employees,
    attendance_list,
    attendance_me,
    attendance_payroll,
    attendance_rules,
    attendance_summary,
    attendance_context,
    attendance_overtime_list,
    attendance_overtime_verify,
    attendance_monthly_hours,
    leave_request_list,
    leave_request_detail,
    leave_request_approve,
    leave_request_reject,
    leave_request_conflicts,
    leave_request_calendar,
    check_in,
    check_out,
    attendance_break_start,
    attendance_break_end,
)

urlpatterns = [
    # Support both with and without trailing slashes for POST safety (no 404 redirects)
    path('attendance/check-in/', check_in, name='attendance-check-in'),
    path('attendance/check-in', check_in),
    path('attendance/check-out/', check_out, name='attendance-check-out'),
    path('attendance/check-out', check_out),
    path('attendance/break/start/', attendance_break_start, name='attendance-break-start'),
    path('attendance/break/start', attendance_break_start),
    path('attendance/break/end/', attendance_break_end, name='attendance-break-end'),
    path('attendance/break/end', attendance_break_end),
    path('attendance/context/', attendance_context, name='attendance-context'),
    path('attendance/', attendance_list, name='attendance-list'),
    path('attendance/me/', attendance_me, name='attendance-me'),
    path('attendance/summary/', attendance_summary, name='attendance-summary'),
    path('attendance/rules/', attendance_rules, name='attendance-rules'),
    path('attendance/employees/', attendance_employees, name='attendance-employees'),
    path('attendance/payroll/', attendance_payroll, name='attendance-payroll'),
    path('attendance/overtime/', attendance_overtime_list, name='attendance-overtime-list'),
    path('attendance/overtime/verify/', attendance_overtime_verify, name='attendance-overtime-verify'),
    path('attendance/monthly-hours/', attendance_monthly_hours, name='attendance-monthly-hours'),
    path('attendance/leave-requests/', leave_request_list, name='leave-request-list'),
    path('attendance/leave-requests/<int:pk>/', leave_request_detail, name='leave-request-detail'),
    path('attendance/leave-requests/<int:pk>/approve/', leave_request_approve, name='leave-request-approve'),
    path('attendance/leave-requests/<int:pk>/reject/', leave_request_reject, name='leave-request-reject'),
    path('attendance/leave-requests/conflicts/', leave_request_conflicts, name='leave-request-conflicts'),
    path('attendance/leave-requests/calendar/', leave_request_calendar, name='leave-request-calendar'),
]
