# Generated by Django 5.2.4 on 2025-11-24 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hremployee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=50)),
                ('proof_document', models.FileField(blank=True, upload_to='employee_documents/bank_proofs/%Y/%m/%d/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('exemption_reason', models.TextField(blank=True)),
                ('exemption_granted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('visa', 'Visa'), ('emirates_id', 'Emirates ID'), ('address_proof', 'Address Proof'), ('certificate', 'Certificate')], max_length=50)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/%d/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_exempted', models.BooleanField(default=False)),
                ('bank_exemption_reason', models.TextField(blank=True)),
                ('bank_exempted_at', models.DateTimeField(blank=True, null=True)),
                ('other_exemptions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('child', 'Child')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('reference_verified', models.BooleanField(default=False)),
                ('bank_verified', models.BooleanField(default=False)),
                ('address_proof_verified', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeVerificationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('personal', 'Personal Details'), ('family', 'Family Details'), ('contact', 'Contact Info'), ('references', 'References'), ('bank', 'Bank Details'), ('government', 'Government ID'), ('address', 'Address Proof')], max_length=20)),
                ('draft_data', models.JSONField(default=dict)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('behavior', 'Behavior'), ('attendance', 'Attendance'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('reason', models.TextField()),
                ('behavior_index_score', models.FloatField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('delivery_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10)),
                ('purpose', models.CharField(choices=[('phone_verification', 'Phone Verification'), ('reference_verification', 'Reference Verification')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='hremployee',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='salary_status',
            field=models.CharField(choices=[('ON_HOLD', 'On Hold'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ON_HOLD', max_length=20),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='verification_status',
            field=models.CharField(blank=True, default='not_started', max_length=50),
        ),
        migrations.AddIndex(
            model_name='hremployee',
            index=models.Index(fields=['salary_status'], name='hr_hremploy_salary__9cb456_idx'),
        ),
        migrations.AddIndex(
            model_name='hremployee',
            index=models.Index(fields=['verification_status'], name='hr_hremploy_verific_17479d_idx'),
        ),
        migrations.AddIndex(
            model_name='hremployee',
            index=models.Index(fields=['department'], name='hr_hremploy_departm_56b89a_idx'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='exemption_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exempted_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeemergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeeexemption',
            name='bank_exempted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_bank_exemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeexemption',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exemption', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeefamilymember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeereference',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeeverification',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='employeeverificationdraft',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_drafts', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='salarystatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarystatuslog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_status_logs', to='hr.hremployee'),
        ),
        migrations.AddIndex(
            model_name='employeebankdetails',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_f9b21e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'document_type'], name='hr_employee_employe_a9f87b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_978edf_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['expiry_date'], name='hr_employee_expiry__f15b25_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeemergencycontact',
            index=models.Index(fields=['employee', 'is_primary'], name='hr_employee_employe_2caa00_idx'),
        ),
        migrations.AddIndex(
            model_name='employeefamilymember',
            index=models.Index(fields=['employee', 'relationship'], name='hr_employee_employe_c9cce7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeereference',
            index=models.Index(fields=['employee', 'otp_verified'], name='hr_employee_employe_a004b5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeverificationdraft',
            index=models.Index(fields=['employee', 'step'], name='hr_employee_employe_32ff66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeverificationdraft',
            unique_together={('employee', 'step')},
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['employee', 'warning_type'], name='hr_hrwarnin_employe_7a9625_idx'),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['employee', 'severity'], name='hr_hrwarnin_employe_0b64af_idx'),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['issued_at'], name='hr_hrwarnin_issued__56e7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['employee', 'purpose'], name='hr_otpverif_employe_bcdcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['otp_code', 'is_used'], name='hr_otpverif_otp_cod_2b7608_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='hr_otpverif_expires_449d79_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystatuslog',
            index=models.Index(fields=['employee', 'changed_at'], name='hr_salaryst_employe_c4a665_idx'),
        ),
    ]
