# Generated by Django 5.2.4 on 2025-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_data_migration_existing_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('reference_verification', 'Reference Verification')], max_length=30),
        ),
    ]
