# Generated by Django 5.2.4 on 2025-11-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_add_deduction_fields'),
        ('hr', '0006_add_bank_verification_request_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='warning_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.IntegerField(help_text='Escalation level (1-4)')),
                ('escalation_reason', models.TextField()),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-escalated_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('explanation_submitted', 'Explanation Submitted'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('access_locked', 'Access Locked'), ('access_unlocked', 'Access Unlocked'), ('salary_held', 'Salary Held'), ('salary_released', 'Salary Released'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='escalation_level',
            field=models.IntegerField(default=0, help_text='Escalation level (1-4)'),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='explanation_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='portal_access_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='reference_attendance',
            field=models.ForeignKey(blank=True, help_text='Reference to attendance record if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='salary_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='status',
            field=models.CharField(choices=[('pending_explanation', 'Pending Explanation'), ('explanation_submitted', 'Explanation Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending_explanation', max_length=30),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='violation_category',
            field=models.CharField(choices=[('late_arrival', 'Late Arrival'), ('unapproved_absence', 'Unapproved Absence'), ('early_exit', 'Early Exit'), ('behavioral', 'Behavioral'), ('manual', 'Manual')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='hrwarning',
            name='violation_date',
            field=models.DateTimeField(blank=True, help_text='Date and time of the violation', null=True),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['status'], name='hr_hrwarnin_status_1826fe_idx'),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['violation_category'], name='hr_hrwarnin_violati_8a83f6_idx'),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['portal_access_locked'], name='hr_hrwarnin_portal__f4ec8f_idx'),
        ),
        migrations.AddIndex(
            model_name='hrwarning',
            index=models.Index(fields=['escalation_level'], name='hr_hrwarnin_escalat_b3be1c_idx'),
        ),
        migrations.AddField(
            model_name='warningattachment',
            name='warning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hr.hrwarning'),
        ),
        migrations.AddField(
            model_name='warningescalation',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='System or admin who escalated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_warnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warningescalation',
            name='warning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='hr.hrwarning'),
        ),
        migrations.AddField(
            model_name='warningexplanation',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_explanations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warningexplanation',
            name='warning',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='hr.hrwarning'),
        ),
        migrations.AddField(
            model_name='warninglog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warninglog',
            name='warning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hr.hrwarning'),
        ),
        migrations.AddIndex(
            model_name='warningattachment',
            index=models.Index(fields=['warning', 'uploaded_at'], name='hr_warninga_warning_189d76_idx'),
        ),
        migrations.AddIndex(
            model_name='warningescalation',
            index=models.Index(fields=['warning', 'escalation_level'], name='hr_warninge_warning_036f78_idx'),
        ),
        migrations.AddIndex(
            model_name='warningescalation',
            index=models.Index(fields=['escalated_at'], name='hr_warninge_escalat_4f5ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='warninglog',
            index=models.Index(fields=['warning', 'timestamp'], name='hr_warningl_warning_a7a44f_idx'),
        ),
        migrations.AddIndex(
            model_name='warninglog',
            index=models.Index(fields=['action', 'timestamp'], name='hr_warningl_action_e7ede6_idx'),
        ),
    ]
