# Generated by Django 5.2.4 on 2025-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_add_warning_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningexplanation',
            name='explanation_text',
            field=models.TextField(max_length=5000),
        ),
    ]
