# Generated by Django 5.2.4 on 2025-11-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_warningexplanation_explanation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
