# Generated by Django 5.2.4 on 2025-11-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_add_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='address_proof_type',
            field=models.CharField(blank=True, choices=[('tenancy_contract', 'Tenancy Contract'), ('dewa_bill', 'DEWA Bill')], help_text="Required if document_type is 'address_proof'", max_length=20, null=True),
        ),
    ]
