# Generated by Django 5.0.7 on 2025-12-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employeesalaryexemption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeesuspension',
            new_name='hr_employee_employe_cba133_idx',
            old_name='hr_employees_employee_idx',
        ),
        migrations.RenameIndex(
            model_name='employeesuspension',
            new_name='hr_employee_expiry__8ba0d3_idx',
            old_name='hr_employees_expiry_d_idx',
        ),
        migrations.RenameIndex(
            model_name='employeesuspension',
            new_name='hr_employee_is_acti_738a55_idx',
            old_name='hr_employees_is_acti_idx',
        ),
    ]
