# Generated by Django 5.0.7 on 2025-12-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_call_matrix_call_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
