# Generated by Django 5.0.7 on 2025-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_profile_tag_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_profile_ea55d1_idx',
            old_name='clients_cli_profile_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('website', 'Website Form'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'Email'), ('phone', 'Phone')], help_text='Source channel (for Online clients)', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='account_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise'), ('government', 'Government')], help_text='Account type (for B2B clients)', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='trn',
            field=models.CharField(blank=True, help_text='Tax Registration Number (for B2B clients)', max_length=50),
        ),
    ]
