# Generated by Django 5.0.7 on 2025-11-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_clients_cli_profile_idx_clients_cli_profile_ea55d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='counter_number',
            field=models.IntegerField(blank=True, help_text='Counter number (1-4) for Walk-In clients', null=True),
        ),
    ]
