# Generated by Django 5.0.7 on 2025-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_organization_counter_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_cli_profile_ea55d1_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='profile_tag',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='source_channel',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='counter_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='trn',
        ),
    ]
