# Generated by Django 5.0.7 on 2025-12-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_clients_cli_profile_ea55d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(blank=True, choices=[('smb', 'SMB'), ('enterprise', 'Enterprise')], max_length=20, null=True),
        ),
    ]
