# Generated by Django 5.2.1 on 2025-09-25 14:11
# Modified to safely handle existing column

from django.db import migrations, models


class SafeAddField(migrations.AddField):
    """AddField that safely handles the case where the column already exists."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Override to safely handle existing column."""
        # Check if column exists in database
        try:
            model = from_state.apps.get_model(app_label, self.model_name)
            table_name = model._meta.db_table
            vendor = schema_editor.connection.vendor
            cursor = schema_editor.connection.cursor()
            
            if vendor == "mysql":
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s
                    """,
                    [table_name, self.name],
                )
                exists = cursor.fetchone()[0] > 0
            elif vendor == "sqlite":
                cursor.execute(f'PRAGMA table_info("{table_name}")')
                columns = {row[1]: row for row in cursor.fetchall()}
                exists = self.name in columns
            else:  # PostgreSQL
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM information_schema.columns
                    WHERE table_name = %s AND column_name = %s
                    """,
                    [table_name, self.name],
                )
                exists = cursor.fetchone()[0] > 0
            
            # If column exists, skip the database operation
            if exists:
                return
            
            # Column doesn't exist, proceed with adding it
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            # If anything goes wrong, try to add the field anyway
            try:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
            except Exception:
                # If add fails, assume column already exists
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        SafeAddField(
            model_name='user',
            name='org_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
