# Generated by Django 5.0.7 on 2025-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matrix_access_token',
            field=models.TextField(blank=True, help_text='Matrix access token (encrypted in production)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matrix_synced',
            field=models.BooleanField(default=False, help_text='Whether this user has been synced to Matrix'),
        ),
        migrations.AddField(
            model_name='user',
            name='matrix_user_id',
            field=models.CharField(blank=True, help_text='Matrix user ID (e.g. @username:chat.local)', max_length=255, null=True),
        ),
    ]
