"""
Django settings for crm_backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ
import sys
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment
env = environ.Env(
    DEBUG=(bool, True),
)
environ.Env.read_env(env_file=str(BASE_DIR / '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')  # No default - must be set in environment
if not SECRET_KEY or len(SECRET_KEY) < 50:
    raise ValueError("SECRET_KEY must be set in environment and be at least 50 characters")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# ALLOWED_HOSTS: Ensure api.crm.click2print.store is always included
# Read from environment, but always include the production API host
_allowed_hosts_from_env = env.list('ALLOWED_HOSTS', default=[])
# Required production host - always include
_required_hosts = ['api.crm.click2print.store']
# Development hosts (only add if DEBUG=True)
if DEBUG:
    _dev_hosts = ['localhost', '127.0.0.1']
else:
    _dev_hosts = []
# Merge: required hosts + env hosts + dev hosts (if DEBUG)
# Use set() to remove duplicates, then convert back to list
ALLOWED_HOSTS = list(set(_required_hosts + _allowed_hosts_from_env + _dev_hosts))

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
else:
    # Development settings
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    # Third-party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'django_filters',
    'channels',

    # Local apps
    'accounts',
    'clients',
    'orders',
    'inventory',
    'delivery',
    'monitoring',
    'mediahub',
    'notifications',
    'hr',
    'attendance',
    'audit',
    'chat',  # Chat app disabled (using Matrix instead) but kept in INSTALLED_APPS for migrations
    'activity_log',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crm_backend.middleware.DatabaseConnectionCleanupMiddleware',  # Ensure DB connections are closed
]

ROOT_URLCONF = 'crm_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_backend.wsgi.application'
ASGI_APPLICATION = 'crm_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Get base database configuration
db_config = env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')

# Configure connection pooling for ASGI compatibility
# CONN_MAX_AGE=0 forces fresh connections for each request, ensuring proper cleanup
# This prevents "Application instance took too long to shut down" warnings
# For better performance in production, consider CONN_MAX_AGE=60 with proper connection management
CONN_MAX_AGE = env.int('DB_CONN_MAX_AGE', default=0)

# Merge connection max age into database config
if isinstance(db_config, dict):
    db_config['CONN_MAX_AGE'] = CONN_MAX_AGE
    # Add connection timeout options
    if 'OPTIONS' not in db_config:
        db_config['OPTIONS'] = {}
    db_config['OPTIONS']['connect_timeout'] = 10

DATABASES = {
    'default': db_config
}

# Use SQLite for tests (faster and doesn't require PostgreSQL server)
# Detect if we're running tests by checking for pytest or test in command line
if 'pytest' in sys.modules or any('test' in arg for arg in sys.argv):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',  # Use in-memory SQLite for fastest test execution
    }

AUTH_USER_MODEL = 'accounts.User'

# Internationalization


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR / 'staticfiles')

MEDIA_URL = env('MEDIA_URL', default='/uploads/')
MEDIA_ROOT = env('MEDIA_ROOT', default=str(BASE_DIR / 'media' / 'uploads'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'SIGNING_KEY': env('JWT_SIGNING_KEY'),  # No default - must be set separately
}
if not SIMPLE_JWT['SIGNING_KEY']:
    raise ValueError("JWT_SIGNING_KEY must be set in environment")

SPECTACULAR_SETTINGS = {
    'TITLE': 'CRM Backend API',
    'DESCRIPTION': 'API for CRM frontend integration',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'https://app.crm.click2print.store',
    'https://api.crm.click2print.store',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:3002',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://127.0.0.1:3002',
])
# Allow all origins in development for easier debugging
# Explicitly set to False - don't rely on DEBUG value
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOW_CREDENTIALS = True

# Allow custom device header used by the frontend when checking in/out
from corsheaders.defaults import default_headers
base_headers = list(default_headers) + [
    'x-device-id',
    'x-device-name',
    'authorization',  # lowercase for CORS
    'Authorization',  # uppercase for compatibility
    'x-log-key',
    'x-log-signature',
    'x-request-id',
]

# Additional CORS settings for development
if DEBUG:
    CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD']
    # Explicitly list all headers - '*' doesn't work reliably in CORS_ALLOW_HEADERS
    CORS_ALLOW_HEADERS = base_headers + [
        'content-type',
        'Content-Type',
        'accept',
        'Accept',
    ]
else:
    CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD']
    CORS_ALLOW_HEADERS = base_headers  # Use specific headers in production

# CORS validation - prevent misconfiguration
if not DEBUG and CORS_ALLOW_ALL_ORIGINS:
    raise ValueError("CORS_ALLOW_ALL_ORIGINS cannot be True in production")
if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ValueError("CORS_ALLOWED_ORIGINS must be set in production")

# Cache configuration (using local memory - no Redis needed)
# For production with Redis, uncomment and configure REDIS_URL in .env
# CACHES = {
#     'default': env.cache('REDIS_URL', default='locmemcache://')
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# DRF throttling: basic defaults and burst control
REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = [
    'rest_framework.throttling.AnonRateThrottle',
    'rest_framework.throttling.UserRateThrottle',
]
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'anon': env('THROTTLE_ANON', default='100/min'),
    'user': env('THROTTLE_USER', default='1000/min'),
}

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=env('REDIS_URL', default='redis://localhost:6379/0'))
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
# Enable eager mode for development (runs tasks synchronously without Celery worker)
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=DEBUG)
# Note: Worker pool is configured in crm_backend/celery.py for Windows compatibility

# Exports dir
EXPORTS_DIR = env('EXPORTS_DIR', default=str(BASE_DIR / 'media' / 'exports'))

# TURN Server Configuration
TURN_SERVER_URL = env('TURN_SERVER_URL', default='turn:localhost:3478')
TURN_SERVER_USERNAME = env('TURN_SERVER_USERNAME', default='turnuser')
TURN_SERVER_PASSWORD = env('TURN_SERVER_PASSWORD', default='turnpass')
TURN_SHARED_SECRET = env('TURN_SHARED_SECRET', default='2OzimVpRm5Jani7NM8VsqZpaP6rrUjZeZs8LBj1ud-4')
TURN_REALM = env('TURN_REALM', default='localhost')
TURN_CREDENTIALS_EXPIRY = env.int('TURN_CREDENTIALS_EXPIRY', default=3600)  # 1 hour

# Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [env('CHANNELS_REDIS_URL', default=env('REDIS_URL', default='redis://localhost:6379/1'))],
            'capacity': 1500,  # Max messages per channel
            'expiry': 10,  # Message expiry in seconds
            'group_expiry': 86400,  # Group expiry (24 hours)
            'prefix': 'chat',  # Redis key prefix
        },
    },
}

# Note: Warnings about "Application instance took too long to shut down" are common
# when using ProtocolTypeRouter with synchronous views. These warnings are typically
# harmless and don't affect functionality. They occur because Channels tries to clean
# up the async application instance after synchronous HTTP requests complete.
# To reduce these warnings in production, consider:
# 1. Using an ASGI server with longer shutdown timeout (e.g., Uvicorn with --timeout-keep-alive)
# 2. Converting heavy synchronous views to async views where possible
# 3. Ensuring database operations complete before response is sent

# Matrix (Synapse) Configuration
# Auto-detect if we're running in Docker or on host
# When running management commands from host, use localhost
# When running in Docker, use synapse hostname
import socket
try:
    socket.gethostbyname('synapse')
    # Can resolve synapse, we're in Docker network
    _default_matrix_url = 'http://synapse:8008'
except (socket.gaierror, OSError):
    # Cannot resolve synapse, we're on host machine
    _default_matrix_url = 'http://localhost:8008'

MATRIX_BASE_URL = env('MATRIX_BASE_URL', default=_default_matrix_url)
MATRIX_SERVER_NAME = env('MATRIX_SERVER_NAME', default='chat.local')
MATRIX_SHARED_SECRET = env('MATRIX_SHARED_SECRET', default='oiccOwYrwKbOMIwteHWWIOyFAhQQiiri')
MATRIX_ADMIN_ACCESS_TOKEN = env('MATRIX_ADMIN_ACCESS_TOKEN', default=None)
# Frontend Matrix URL (for client connections)
MATRIX_PUBLIC_URL = env('MATRIX_PUBLIC_URL', default='http://localhost:8008')

# Chat settings
MAX_ATTACHMENT_MB = env.int('MAX_ATTACHMENT_MB', default=10)

# Email configuration
# Only use console backend if explicitly set in EMAIL_BACKEND env var
# Don't auto-switch to console just because EMAIL_HOST is empty
email_backend_env = env('EMAIL_BACKEND', default='')
if email_backend_env:
    EMAIL_BACKEND = email_backend_env
else:
    # Default to SMTP backend if not explicitly set
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# Set DEFAULT_FROM_EMAIL to EMAIL_HOST_USER if not explicitly set
EMAIL_FROM = env('EMAIL_FROM', default='')
if not EMAIL_FROM and EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
    SERVER_EMAIL = EMAIL_HOST_USER
elif EMAIL_FROM:
    DEFAULT_FROM_EMAIL = EMAIL_FROM
    SERVER_EMAIL = EMAIL_FROM
else:
    DEFAULT_FROM_EMAIL = 'noreply@crm.click2print.store'
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Celery Beat schedule
# Frequency can be adjusted: more frequent = more accurate timing but higher load
# Options: 900.0 (15 min), 1800.0 (30 min), 3600.0 (1 hour), 7200.0 (2 hours)
CELERY_BEAT_SCHEDULE = {
    'process-scheduled-reports': {
        'task': 'activity_log.tasks.process_scheduled_reports',
        'schedule': env.float('CELERY_BEAT_REPORT_CHECK_INTERVAL', default=3600.0),  # Run every hour by default
    },
    'cleanup-orphaned-uploads': {
        'task': 'chat.tasks.cleanup_orphaned_uploads',
        'schedule': 86400.0,  # Run daily (24 hours)
    },
    # Monitoring system tasks
    'cleanup-monitoring-data': {
        'task': 'monitoring.tasks.cleanup_old_monitoring_data',
        'schedule': 86400.0,  # Run daily (24 hours)
        'kwargs': {'days': 30},  # Retain data for 30 days
    },
    'generate-missing-thumbnails': {
        'task': 'monitoring.tasks.generate_missing_thumbnails',
        'schedule': 3600.0,  # Run hourly
    },
    'update-device-status': {
        'task': 'monitoring.tasks.update_device_status',
        'schedule': 300.0,  # Run every 5 minutes
    },
    'calculate-productivity-metrics': {
        'task': 'monitoring.tasks.calculate_productivity_metrics',
        'schedule': 3600.0,  # Run hourly
    },
    'send-idle-alerts': {
        'task': 'monitoring.tasks.send_idle_alerts',
        'schedule': 900.0,  # Run every 15 minutes
    },
    'end-expired-suspensions': {
        'task': 'hr.tasks.end_expired_suspensions',
        'schedule': 3600.0,  # Run every hour
    },
    'end-expired-exemptions': {
        'task': 'hr.tasks.end_expired_exemptions',
        'schedule': 3600.0,  # Run every hour
    },
}

# Monitoring system settings
MONITORING_STORAGE_PATH = env('MONITORING_STORAGE_PATH', default=str(BASE_DIR / 'monitoring_data'))
STORAGE_DRIVER = env('STORAGE_DRIVER', default='local')  # local or s3
JWT_SECRET = env('JWT_SECRET')  # No default - must be set separately
if not JWT_SECRET:
    raise ValueError("JWT_SECRET must be set in environment")

# Log encryption settings
# LOG_ENCRYPTION_KEY must be a 32-byte key (256 bits) for AES-256 encryption
# Generate with: python -c "import secrets; print(secrets.token_urlsafe(32))"
# Or use: openssl rand -base64 32
# Falls back to SECRET_KEY if not set (see activity_log.utils.encryption for fallback logic)
LOG_ENCRYPTION_KEY = env('LOG_ENCRYPTION_KEY', default=None)
if LOG_ENCRYPTION_KEY and len(LOG_ENCRYPTION_KEY.encode()) != 32:
    raise ValueError("LOG_ENCRYPTION_KEY must be exactly 32 bytes if provided")

# Monitoring logging configuration
import os
from pathlib import Path

# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'monitoring_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'monitoring.log'),
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'monitoring': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.heartbeat': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.screenshot': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.device': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.analytics': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.storage': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'monitoring.performance': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.cleanup': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.websocket': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring.api': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# AWS S3 settings (if using S3 storage)
AWS_S3_BUCKET_NAME = env('AWS_S3_BUCKET_NAME', default=None)
AWS_S3_REGION = env('AWS_S3_REGION', default='us-east-1')
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID', default=None)
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default=None)

# WebRTC Configuration
# STUN servers for NAT traversal (free Google STUN servers)
WEBRTC_STUN_SERVERS = env.list('WEBRTC_STUN_SERVERS', default=[
    'stun:stun.l.google.com:19302',
    'stun:stun1.l.google.com:19302',
])

# TURN server configuration (optional, for production)
# For production, use a TURN server service like Twilio, AWS Kinesis, or self-hosted coturn
WEBRTC_TURN_SERVER_URL = env('WEBRTC_TURN_SERVER_URL', default=None)
WEBRTC_TURN_USERNAME = env('WEBRTC_TURN_USERNAME', default=None)
WEBRTC_TURN_CREDENTIAL = env('WEBRTC_TURN_CREDENTIAL', default=None)

# Build WebRTC configuration for API responses
def get_webrtc_config():
    """Get WebRTC configuration for frontend"""
    config = {
        'iceServers': []
    }
    
    # Add STUN servers
    for stun_url in WEBRTC_STUN_SERVERS:
        config['iceServers'].append({
            'urls': [stun_url]
        })
    
    # Add TURN server if configured
    if WEBRTC_TURN_SERVER_URL:
        turn_config = {
            'urls': [WEBRTC_TURN_SERVER_URL]
        }
        if WEBRTC_TURN_USERNAME:
            turn_config['username'] = WEBRTC_TURN_USERNAME
        if WEBRTC_TURN_CREDENTIAL:
            turn_config['credential'] = WEBRTC_TURN_CREDENTIAL
        config['iceServers'].append(turn_config)
    
    return config