# Generated by Django 5.0.7 on 2025-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['sku']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('raw_materials', 'Raw Materials'), ('finished_goods', 'Finished Goods'), ('supplies', 'Supplies'), ('consumables', 'Consumables'), ('equipment', 'Equipment')], default='raw_materials', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit in AED', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.IntegerField(default=7, help_text='Lead time in days for restocking'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, help_text='Location/Bin (e.g., A1-R2-S3)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_stock',
            field=models.IntegerField(default=0, help_text='Minimum stock level (reorder point)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_quantity',
            field=models.IntegerField(default=0, help_text='Quantity to reorder when below minimum'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved',
            field=models.IntegerField(default=0, help_text='Reserved quantity (not available)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price per unit in AED', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier_id',
            field=models.CharField(blank=True, help_text='Preferred supplier ID or name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.CharField(choices=[('main', 'Main Warehouse'), ('secondary', 'Secondary'), ('offsite', 'Offsite')], default='main', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(default='pcs', max_length=32),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_item_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['category'], name='inventory_item_category_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['warehouse'], name='inventory_item_warehouse_idx'),
        ),
    ]
