# Generated by Django 5.2.4 on 2025-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_options_inventoryitem_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(help_text='Auto-generated machine code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Machine name (e.g., Epson SureColor S60600)', max_length=255)),
                ('type', models.CharField(choices=[('digital_printer', 'Digital Printer'), ('offset_printer', 'Offset Printer'), ('uv_printer', 'UV Printer'), ('dtf_printer', 'DTF Printer'), ('screen_printer', 'Screen Printer'), ('laser_cutter', 'Laser Cutter'), ('laminator', 'Laminator'), ('creasing_machine', 'Creasing Machine'), ('binding_machine', 'Binding Machine'), ('embroidery_machine', 'Embroidery Machine'), ('heat_press', 'Heat Press')], help_text='Machine type', max_length=50)),
                ('brand', models.CharField(blank=True, help_text='Brand name (e.g., Epson)', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Model number (e.g., S60600)', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Serial number', max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Purchase date', null=True)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('location', models.CharField(choices=[('dubai', 'Dubai'), ('pakistan', 'Pakistan')], default='dubai', help_text='Machine location', max_length=50)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('repair', 'Needs Repair'), ('offline', 'Offline')], default='operational', help_text='Current status', max_length=50)),
                ('running_hours', models.FloatField(default=0.0, help_text='Current running hours')),
                ('service_interval_hours', models.IntegerField(default=500, help_text='Service interval in hours')),
                ('next_service_due', models.DateField(blank=True, help_text='Next service due date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['machine_code'],
                'indexes': [models.Index(fields=['machine_code'], name='machine_code_idx'), models.Index(fields=['type'], name='machine_type_idx'), models.Index(fields=['location'], name='machine_location_idx'), models.Index(fields=['status'], name='machine_status_idx')],
            },
        ),
    ]
