# Generated by Django 4.2.23 on 2025-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productseo',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=511),
        ),
    ]
