# Generated by Django 5.2.9 on 2025-12-10 16:30

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0002_add_missing_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(
                default=0.0,
                help_text='Allowed values: 0, 0.5, 1, ... , 5',
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0)
                ]
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
