# Generated by Django 5.2.9 on 2025-12-10 16:30

from django.db import migrations, models
import django.core.validators


def add_rating_fields_if_not_exist(apps, schema_editor):
    """Safely add rating fields if they don't exist in the database"""
    # Since rating and rating_count already exist in 0001_initial, we skip adding them
    # This function is mainly for databases that were created before 0001_initial
    # For SQLite, we skip entirely to avoid issues
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    # For PostgreSQL/MySQL, the fields should already exist from 0001_initial
    # So we don't need to do anything here
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0002_add_missing_long_description'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip adding fields since they already exist in 0001_initial
                migrations.RunPython(add_rating_fields_if_not_exist, noop_reverse),
            ],
            state_operations=[
                # Don't try to add fields to state since 0001_initial already has them
                # This prevents "duplicate column" errors
            ],
        ),
    ]
