# Generated by Django 4.2.23 on 2025-09-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0003_orders_device_uuid_user_address_user_emirates_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSEO',
        ),
    ]
