# Generated by Django 4.2.23 on 2025-09-17 18:19

from django.db import migrations


def delete_blogcategorymap_if_exists(apps, schema_editor):
    """Safely delete BlogCategoryMap table if it exists in the database"""
    db_table = 'admin_backend_final_blogcategorymap'
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_name=%s
            """, [db_table])
        elif schema_editor.connection.vendor == 'mysql':
            cursor.execute("""
                SELECT TABLE_NAME 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA=DATABASE() 
                AND TABLE_NAME=%s
            """, [db_table])
        else:  # sqlite
            # SQLite: Skip table deletion since these tables don't exist in 0001_initial
            # and SQLite has issues with parameter formatting in Django's debug layer
            # For local SQLite databases, these tables won't exist anyway
            return
        
        if cursor.fetchone():
            if schema_editor.connection.vendor == 'postgresql':
                cursor.execute(f'DROP TABLE IF EXISTS {db_table} CASCADE')
            elif schema_editor.connection.vendor == 'mysql':
                cursor.execute(f'DROP TABLE IF EXISTS {db_table}')


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0004_delete_blogseo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Safely delete BlogCategoryMap table from database if it exists
                migrations.RunPython(delete_blogcategorymap_if_exists, noop_reverse),
            ],
            state_operations=[
                # Don't try to delete BlogCategoryMap from state since 0001_initial doesn't have it
                # This prevents KeyError during merge migrations
            ],
        ),
    ]
