# Generated by Django 5.2.9 on 2025-12-10 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0004_add_productimage_caption_fields'),
    ]

    # NOTE:
    # This migration originally recreated models/fields that are already
    # created in 0001_initial, which caused \"table already exists\" and
    # \"duplicate column\" errors on fresh databases (especially in tests).
    # It is now intentionally a no-op. The migration remains in the graph
    # so Django's migration history is consistent, but running it has no
    # effect on databases that already contain these tables/columns.
    operations = []
