# Generated by Django 4.2.23 on 2025-09-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0005_delete_blogcategorymap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
