# Generated by Django 5.0.14 on 2025-12-12 13:29

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing ProductSEO records using raw SQL"""
    # Check if slug column exists first
    db_table = 'admin_backend_final_productseo'
    with schema_editor.connection.cursor() as cursor:
        # Check if slug column exists
        slug_exists = False
        if schema_editor.connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name=%s AND column_name='slug'
            """, [db_table])
            slug_exists = cursor.fetchone() is not None
        elif schema_editor.connection.vendor == 'mysql':
            cursor.execute("""
                SELECT COLUMN_NAME 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA=DATABASE() 
                AND TABLE_NAME=%s AND COLUMN_NAME='slug'
            """, [db_table])
            slug_exists = cursor.fetchone() is not None
        else:  # sqlite
            cursor.execute("PRAGMA table_info(admin_backend_final_productseo)")
            columns = [row[1] for row in cursor.fetchall()]
            slug_exists = 'slug' in columns
        
        if not slug_exists:
            # Column doesn't exist yet, skip population
            # The column will be added by the state_operations
            return
        
        # Get all ProductSEO records with their products (only those without slugs)
        if schema_editor.connection.vendor == 'sqlite':
            cursor.execute("""
                SELECT ps.seo_id, p.product_id, p.title
                FROM admin_backend_final_productseo ps
                JOIN admin_backend_final_product p ON ps.product_id = p.product_id
                WHERE ps.slug IS NULL OR ps.slug = ''
            """)
        else:
            cursor.execute("""
                SELECT ps.seo_id, p.product_id, p.title
                FROM admin_backend_final_productseo ps
                JOIN admin_backend_final_product p ON ps.product_id = p.product_id
                WHERE ps.slug IS NULL OR ps.slug = ''
            """)
        
        rows = cursor.fetchall()
        
        for seo_id, product_id, product_title in rows:
            product_title = product_title or ''
            base_slug = slugify(product_title) or f"product-{product_id}"
            
            # Check for uniqueness using raw SQL
            slug = base_slug
            counter = 1
            while True:
                if schema_editor.connection.vendor == 'sqlite':
                    cursor.execute(
                        "SELECT COUNT(*) FROM admin_backend_final_productseo WHERE slug = ? AND seo_id != ?",
                        [slug, seo_id]
                    )
                else:
                    cursor.execute(
                        "SELECT COUNT(*) FROM admin_backend_final_productseo WHERE slug = %s AND seo_id != %s",
                        [slug, seo_id]
                    )
                if cursor.fetchone()[0] == 0:
                    break
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            # Update the slug using raw SQL
            if schema_editor.connection.vendor == 'sqlite':
                cursor.execute(
                    "UPDATE admin_backend_final_productseo SET slug = ? WHERE seo_id = ?",
                    [slug, seo_id]
                )
            else:
                cursor.execute(
                    "UPDATE admin_backend_final_productseo SET slug = %s WHERE seo_id = %s",
                    [slug, seo_id]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0007_add_cartitem_selected_attributes'),
    ]

    operations = [
        # First, add the slug column to the database if it doesn't exist
        migrations.AddField(
            model_name='productseo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        # Then populate it with data
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Finally, alter it to add the db_index
        migrations.AlterField(
            model_name='productseo',
            name='slug',
            field=models.SlugField(max_length=255, db_index=True),
        ),
    ]
