# Generated by Django 5.0.14 on 2025-12-12 13:29

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing ProductSEO records using raw SQL"""
    Product = apps.get_model('admin_backend_final', 'Product')
    ProductSEO = apps.get_model('admin_backend_final', 'ProductSEO')
    
    # Use raw SQL to avoid FieldError since model state doesn't have slug yet
    with schema_editor.connection.cursor() as cursor:
        # Get all ProductSEO records with their products
        if schema_editor.connection.vendor == 'sqlite':
            cursor.execute("""
                SELECT ps.seo_id, p.product_id, p.title
                FROM admin_backend_final_productseo ps
                JOIN admin_backend_final_product p ON ps.product_id = p.product_id
                WHERE ps.slug IS NULL OR ps.slug = ''
            """)
        else:
            cursor.execute("""
                SELECT ps.seo_id, p.product_id, p.title
                FROM admin_backend_final_productseo ps
                JOIN admin_backend_final_product p ON ps.product_id = p.product_id
                WHERE ps.slug IS NULL OR ps.slug = ''
            """)
        
        rows = cursor.fetchall()
        
        for seo_id, product_id, product_title in rows:
            product_title = product_title or ''
            base_slug = slugify(product_title) or f"product-{product_id}"
            
            # Check for uniqueness using raw SQL
            slug = base_slug
            counter = 1
            while True:
                if schema_editor.connection.vendor == 'sqlite':
                    cursor.execute(
                        "SELECT COUNT(*) FROM admin_backend_final_productseo WHERE slug = ? AND seo_id != ?",
                        [slug, seo_id]
                    )
                else:
                    cursor.execute(
                        "SELECT COUNT(*) FROM admin_backend_final_productseo WHERE slug = %s AND seo_id != %s",
                        [slug, seo_id]
                    )
                if cursor.fetchone()[0] == 0:
                    break
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            # Update the slug using raw SQL
            if schema_editor.connection.vendor == 'sqlite':
                cursor.execute(
                    "UPDATE admin_backend_final_productseo SET slug = ? WHERE seo_id = ?",
                    [slug, seo_id]
                )
            else:
                cursor.execute(
                    "UPDATE admin_backend_final_productseo SET slug = %s WHERE seo_id = %s",
                    [slug, seo_id]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0007_add_cartitem_selected_attributes'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to update Django's state without modifying DB
        # since the column already exists in the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Populate slugs using raw SQL (avoids FieldError)
                migrations.RunPython(populate_slugs, migrations.RunPython.noop),
            ],
            state_operations=[
                # Update Django's migration state to include the slug field
                migrations.AddField(
                    model_name='productseo',
                    name='slug',
                    field=models.SlugField(blank=True, max_length=255, null=True),
                ),
                migrations.AlterField(
                    model_name='productseo',
                    name='slug',
                    field=models.SlugField(max_length=255, db_index=True),
                ),
            ],
        ),
    ]
