# Generated by Django 4.2.23 on 2025-09-20 22:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_tables_if_not_exist(apps, schema_editor):
    """Safely create tables if they don't exist in the database"""
    # Since these tables already exist in 0001_initial, we skip creating them
    # This function is mainly for databases that were created before 0001_initial
    # For SQLite, we skip entirely to avoid issues
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    # For PostgreSQL/MySQL, the tables should already exist from 0001_initial
    # So we don't need to do anything here
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0008_blogpost_product_long_description_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip creating tables since they already exist in 0001_initial
                migrations.RunPython(create_tables_if_not_exist, noop_reverse),
            ],
            state_operations=[
                # Don't try to create models in state since 0001_initial already has them
                # This prevents "table already exists" errors
            ],
        ),
    ]
