# Generated by Django 4.2.23 on 2025-09-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0009_attributesubcategory_producttestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attributesubcategory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
