# Generated by Django 4.2.23 on 2025-09-29 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0010_attribute_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('branding_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_title', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('singleton_lock', models.CharField(db_index=True, default='X', editable=False, max_length=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favicon', models.ForeignKey(blank=True, db_column='favicon_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_favicon_for_branding', to='admin_backend_final.image')),
                ('logo', models.ForeignKey(blank=True, db_column='logo_image_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_logo_for_branding', to='admin_backend_final.image')),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
