# Generated by Django 4.2.23 on 2025-10-07 16:00

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


def remove_callbackrequest_fields_if_exist(apps, schema_editor):
    """Safely remove callbackrequest fields if they exist in the database"""
    db_table = 'admin_backend_final_callbackrequest'
    fields_to_remove = ['contact_info', 'message', 'sender_id']
    
    with schema_editor.connection.cursor() as cursor:
        for field_name in fields_to_remove:
            # Check if column exists
            if schema_editor.connection.vendor == 'postgresql':
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name=%s AND column_name=%s
                """, [db_table, field_name])
            elif schema_editor.connection.vendor == 'mysql':
                cursor.execute("""
                    SELECT COLUMN_NAME 
                    FROM INFORMATION_SCHEMA.COLUMNS 
                    WHERE TABLE_SCHEMA=DATABASE() 
                    AND TABLE_NAME=%s AND COLUMN_NAME=%s
                """, [db_table, field_name])
            else:  # sqlite
                cursor.execute("PRAGMA table_info(admin_backend_final_callbackrequest)")
                columns = [row[1] for row in cursor.fetchall()]
                if field_name in columns:
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN {field_name}')
                continue
            
            if cursor.fetchone():
                # Column exists, drop it
                if schema_editor.connection.vendor == 'postgresql':
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN {field_name}')
                elif schema_editor.connection.vendor == 'mysql':
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN {field_name}')


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0012_productcards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Safely remove fields from database if they exist
                migrations.RunPython(remove_callbackrequest_fields_if_exist, noop_reverse),
            ],
            state_operations=[
                # Don't try to remove fields from state since 0001_initial doesn't have them
                # Don't try to add fields to state since 0001_initial already has them
                # This prevents KeyError during merge migrations
                migrations.AlterField(
                    model_name='callbackrequest',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['device_uuid'], name='admin_backe_device__b93823_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['phone_number'], name='admin_backe_phone_n_412d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['status'], name='admin_backe_status_ee5cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['preferred_callback'], name='admin_backe_preferr_5ed92b_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackrequest',
            index=models.Index(fields=['event_datetime'], name='admin_backe_event_d_801f24_idx'),
        ),
    ]
