# Generated by Django 4.2.23 on 2025-10-08 18:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def create_recentlydeleteditem_if_not_exist(apps, schema_editor):
    """Safely create RecentlyDeletedItem table if it doesn't exist in the database"""
    # Since RecentlyDeletedItem already exists in 0001_initial, we skip creating it
    # This function is mainly for databases that were created before 0001_initial
    # For SQLite, we skip entirely to avoid issues
    if schema_editor.connection.vendor == 'sqlite':
        return
    
    # For PostgreSQL/MySQL, the table should already exist from 0001_initial
    # So we don't need to do anything here
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0013_alter_callbackrequest_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip creating table since it already exists in 0001_initial
                migrations.RunPython(create_recentlydeleteditem_if_not_exist, noop_reverse),
            ],
            state_operations=[
                # Don't try to create model in state since 0001_initial already has it
                # This prevents "table already exists" errors
            ],
        ),
    ]
