# Generated by Django 5.2.9 on 2025-12-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0009_create_productcards_table'),
        ('admin_backend_final', '0014_recentlydeleteditem'),
    ]

    operations = [
    ]
