# Generated by Django 5.2.9 on 2026-01-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0016_add_product_to_firstcarouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstcarouselimage',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_carousel_images', to='admin_backend_final.product'),
        ),
    ]
