# Generated by Django 5.2.9 on 2026-01-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0017_alter_firstcarouselimage_product'),
        ('admin_backend_final', '0018_add_product_to_secondcarouselimage'),
    ]

    operations = [
    ]
