# Generated by Django 5.2.9 on 2026-01-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0019_merge_20260119_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondcarouselimage',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_carousel_images', to='admin_backend_final.product'),
        ),
    ]
