# Generated by Django 5.0.14 on 2026-01-22 19:44

from django.db import migrations, models
from django.utils import timezone


def set_initial_updated_at(apps, schema_editor):
    """Set updated_at = created_at for existing images"""
    Image = apps.get_model('admin_backend_final', 'Image')
    for image in Image.objects.all():
        if not image.updated_at:
            image.updated_at = image.created_at if image.created_at else timezone.now()
            image.save(update_fields=['updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0021_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_initial_updated_at, migrations.RunPython.noop),
    ]
