# Generated by Django 5.0.14 on 2026-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_backend_final', '0024_emailverificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
