# Generated by Django 5.2.1 on 2025-09-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Depend on 0001_initial which always exists
        # If 0010 exists, it will be applied before this migration
        ('monitoring', '0001_initial'),
    ]

    operations = [
    ]
