# Generated by Django 5.2.1 on 2025-10-30 20:26

import django.db.models.deletion
from django.db import migrations, models
from app.common.safe_migrations import SafeAlterField


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_device_options_alter_deviceuserbind_options_and_more'),
    ]

    operations = [
        SafeAlterField(
            model_name='session',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='monitoring.device'),
        ),
    ]
