# Generated by Django 5.0.7 on 2025-11-12 14:06
# Modified to safely handle missing indexes and models

from django.db import migrations


class SafeRemoveIndex(migrations.RemoveIndex):
    """RemoveIndex that safely handles missing models in state."""
    
    def state_forwards(self, app_label, state):
        """Override to safely handle missing model in state."""
        # Check if model exists in state
        model_key = (app_label, self.model_name_lower)
        if model_key not in state.models:
            # Model doesn't exist in state, skip
            return
        try:
            super().state_forwards(app_label, state)
        except (KeyError, AttributeError):
            # Index doesn't exist in state, skip
            pass


class SafeRenameIndex(migrations.RenameIndex):
    """RenameIndex that safely handles missing models in state."""
    
    def state_forwards(self, app_label, state):
        """Override to safely handle missing model in state."""
        # Check if model exists in state
        model_key = (app_label, self.model_name_lower)
        if model_key not in state.models:
            # Model doesn't exist in state, skip
            return
        try:
            super().state_forwards(app_label, state)
        except (KeyError, AttributeError):
            # Index doesn't exist in state, skip
            pass


# Indexes to remove
INDEXES_TO_REMOVE = [
    ("monitoring_device", "monitoring__user_id_2d8a6f_idx"),
    ("monitoring_device", "monitoring__org_id_a4f32e_idx"),
    ("monitoring_device", "monitoring__last_he_a0bc81_idx"),
    ("monitoring_device", "monitoring__current_7f50cd_idx"),
    ("monitoring_devicetoken", "monitoring__secret_360dfd_idx"),
    ("monitoring_devicetoken", "monitoring__expires_daf44e_idx"),
    ("monitoring_deviceuserbind", "monitoring__device__7a335e_idx"),
    ("monitoring_deviceuserbind", "monitoring__user_id_ca49b4_idx"),
    ("monitoring_heartbeat", "monitoring__device__8e6a8b_idx"),
    ("monitoring_heartbeat", "monitoring__created_2ebadb_idx"),
    ("monitoring_heartbeat", "monitoring__user_id_ba36c5_idx"),
    ("monitoring_screenshot", "monitoring__device__769863_idx"),
    ("monitoring_screenshot", "monitoring__taken_a_ee5a59_idx"),
    ("monitoring_screenshot", "monitoring__sha256_5b6fa8_idx"),
    ("monitoring_screenshot", "monitoring__user_id_facb23_idx"),
    ("monitoring_session", "monitoring__user_id_368c44_idx"),
    ("monitoring_session", "monitoring__status_4f0151_idx"),
]

# Indexes to rename
INDEXES_TO_RENAME = [
    ("monitoring_idlealert", "monitoring_i_device__f8a8b4_idx", "monitoring__device__22c2fd_idx"),
    ("monitoring_idlealert", "monitoring_i_is_reso_8b2a8b_idx", "monitoring__is_reso_b52c96_idx"),
]


def safe_remove_indexes(apps, schema_editor):
    """Safely remove indexes, checking existence first."""
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    
    for table, index_name in INDEXES_TO_REMOVE:
        try:
            if vendor == "mysql":
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s
                    """,
                    [table, index_name],
                )
                exists = cursor.fetchone()[0]
                if exists:
                    cursor.execute(f"ALTER TABLE `{table}` DROP INDEX `{index_name}`")
            elif vendor == "sqlite":
                # SQLite: Check if index exists by querying sqlite_master
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM sqlite_master
                    WHERE type='index' AND name=?
                    """,
                    [index_name],
                )
                exists = cursor.fetchone()[0]
                if exists:
                    cursor.execute(f"DROP INDEX {index_name}")
            else:
                # PostgreSQL and others
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM pg_indexes
                    WHERE tablename = %s AND indexname = %s
                    """,
                    [table, index_name],
                )
                exists = cursor.fetchone()[0]
                if exists:
                    cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
        except Exception as e:
            # Ignore errors - index might not exist
            pass


def safe_rename_indexes(apps, schema_editor):
    """Safely rename indexes, checking existence first."""
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    
    for table, old_name, new_name in INDEXES_TO_RENAME:
        try:
            if vendor == "mysql":
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND INDEX_NAME = %s
                    """,
                    [table, old_name],
                )
                exists = cursor.fetchone()[0]
                if exists:
                    cursor.execute(f"ALTER TABLE `{table}` RENAME INDEX `{old_name}` TO `{new_name}`")
            elif vendor == "sqlite":
                # SQLite doesn't support RENAME INDEX directly
                # Check if old index exists, and if new one doesn't, we skip
                # (SQLite indexes are typically auto-created with correct names)
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM sqlite_master
                    WHERE type='index' AND name=?
                    """,
                    [old_name],
                )
                old_exists = cursor.fetchone()[0]
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM sqlite_master
                    WHERE type='index' AND name=?
                    """,
                    [new_name],
                )
                new_exists = cursor.fetchone()[0]
                # If old exists and new doesn't, we'd need to recreate - skip for now
                # SQLite typically handles this automatically
                pass
            else:
                # PostgreSQL
                cursor.execute(
                    """
                    SELECT COUNT(*) FROM pg_indexes
                    WHERE tablename = %s AND indexname = %s
                    """,
                    [table, old_name],
                )
                exists = cursor.fetchone()[0]
                if exists:
                    cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
        except Exception as e:
            # Ignore errors - index might not exist or already renamed
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_session_device'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_remove_indexes, migrations.RunPython.noop),
                migrations.RunPython(safe_rename_indexes, migrations.RunPython.noop),
            ],
            state_operations=[
                # Update Django's state to reflect index removals
                # Use SafeRemoveIndex to handle missing models gracefully
                SafeRemoveIndex(
                    model_name='device',
                    name='monitoring__user_id_2d8a6f_idx',
                ),
                SafeRemoveIndex(
                    model_name='device',
                    name='monitoring__org_id_a4f32e_idx',
                ),
                SafeRemoveIndex(
                    model_name='device',
                    name='monitoring__last_he_a0bc81_idx',
                ),
                SafeRemoveIndex(
                    model_name='device',
                    name='monitoring__current_7f50cd_idx',
                ),
                SafeRemoveIndex(
                    model_name='devicetoken',
                    name='monitoring__secret_360dfd_idx',
                ),
                SafeRemoveIndex(
                    model_name='devicetoken',
                    name='monitoring__expires_daf44e_idx',
                ),
                SafeRemoveIndex(
                    model_name='deviceuserbind',
                    name='monitoring__device__7a335e_idx',
                ),
                SafeRemoveIndex(
                    model_name='deviceuserbind',
                    name='monitoring__user_id_ca49b4_idx',
                ),
                SafeRemoveIndex(
                    model_name='heartbeat',
                    name='monitoring__device__8e6a8b_idx',
                ),
                SafeRemoveIndex(
                    model_name='heartbeat',
                    name='monitoring__created_2ebadb_idx',
                ),
                SafeRemoveIndex(
                    model_name='heartbeat',
                    name='monitoring__user_id_ba36c5_idx',
                ),
                SafeRemoveIndex(
                    model_name='screenshot',
                    name='monitoring__device__769863_idx',
                ),
                SafeRemoveIndex(
                    model_name='screenshot',
                    name='monitoring__taken_a_ee5a59_idx',
                ),
                SafeRemoveIndex(
                    model_name='screenshot',
                    name='monitoring__sha256_5b6fa8_idx',
                ),
                SafeRemoveIndex(
                    model_name='screenshot',
                    name='monitoring__user_id_facb23_idx',
                ),
                SafeRemoveIndex(
                    model_name='session',
                    name='monitoring__user_id_368c44_idx',
                ),
                SafeRemoveIndex(
                    model_name='session',
                    name='monitoring__status_4f0151_idx',
                ),
                SafeRenameIndex(
                    model_name='idlealert',
                    new_name='monitoring__device__22c2fd_idx',
                    old_name='monitoring_i_device__f8a8b4_idx',
                ),
                SafeRenameIndex(
                    model_name='idlealert',
                    new_name='monitoring__is_reso_b52c96_idx',
                    old_name='monitoring_i_is_reso_8b2a8b_idx',
                ),
            ],
        ),
    ]
