# Generated by Django 5.2.1 on 2025-11-17 14:51
# Modified to safely handle missing fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from app.common.safe_migrations import SafeRemoveField, SafeAlterField


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_merge_0012_0016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at']},
        ),
        SafeRemoveField(
            model_name='device',
            name='user',
        ),
        SafeAlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
