# Generated by Django 5.2.1 on 2025-11-18 13:29
# Modified to safely handle missing indexes and fields

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models
from app.common.safe_migrations import (
    SafeAddField, SafeAlterField, SafeAddIndex, SafeRemoveIndex,
    SafeRenameIndex, SafeRemoveField
)


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_merge_0007_0018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceuserbind',
            options={'ordering': ['-bound_at']},
        ),
        SafeRemoveIndex(
            model_name='device',
            name='monitoring__current_7f50cd_idx',
        ),
        SafeRemoveIndex(
            model_name='deviceuserbind',
            name='monitoring__device__7a335e_idx',
        ),
        SafeRemoveIndex(
            model_name='deviceuserbind',
            name='monitoring__user_id_ca49b4_idx',
        ),
        SafeRemoveIndex(
            model_name='heartbeat',
            name='monitoring__user_id_ba36c5_idx',
        ),
        SafeRemoveIndex(
            model_name='screenshot',
            name='monitoring__user_id_facb23_idx',
        ),
        SafeRenameIndex(
            model_name='idlealert',
            new_name='monitoring__device__22c2fd_idx',
            old_name='monitoring_i_device__f8a8b4_idx',
        ),
        SafeRenameIndex(
            model_name='idlealert',
            new_name='monitoring__is_reso_b52c96_idx',
            old_name='monitoring_i_is_reso_8b2a8b_idx',
        ),
        SafeRemoveField(
            model_name='device',
            name='user',
        ),
        SafeAddField(
            model_name='deviceuserbind',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        SafeAddField(
            model_name='deviceuserbind',
            name='unbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        SafeAlterField(
            model_name='deviceuserbind',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_binds', to=settings.AUTH_USER_MODEL),
        ),
        SafeAlterField(
            model_name='heartbeat',
            name='user_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        SafeAlterField(
            model_name='idlealert',
            name='id',
            field=models.CharField(default=monitoring.models.generate_session_id, max_length=25, primary_key=True, serialize=False),
        ),
        SafeAlterField(
            model_name='screenshot',
            name='user_role_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        SafeAddIndex(
            model_name='deviceuserbind',
            index=models.Index(fields=['device', 'is_active'], name='monitoring__device__aae339_idx'),
        ),
        SafeAddIndex(
            model_name='deviceuserbind',
            index=models.Index(fields=['user', 'is_active'], name='monitoring__user_id_507023_idx'),
        ),
    ]
