# Generated by Django 5.2.1 on 2025-11-29 16:54
# Modified to use SafeCreateModel for safe migration

import django.db.models.deletion
import monitoring.models
from django.db import migrations, models
from app.common.safe_migrations import SafeCreateModel


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alter_deviceuserbind_options_and_more'),
    ]

    operations = [
        SafeCreateModel(
            name='Recording',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_recording_id, max_length=25, primary_key=True, serialize=False)),
                ('blob_key', models.CharField(max_length=500)),
                ('thumb_key', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.FloatField()),
                ('is_idle_period', models.BooleanField(default=False)),
                ('idle_start_offset', models.FloatField(blank=True, null=True)),
                ('user_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('user_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='monitoring.device')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
