# Generated by Django 5.2.1 on 2025-12-04 14:42
# Modified to use SafeDeleteModel for safe migration

from django.db import migrations
from app.common.safe_migrations import SafeDeleteModel


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_recording'),
    ]

    operations = [
        SafeDeleteModel(
            name='Screenshot',
        ),
    ]
