# Generated by Django 5.0.7 on 2025-12-05 16:05
# Modified to use SafeCreateModel and SafeAddIndex for safe migration

import django.db.models.deletion
import monitoring.models
from django.db import migrations, models
from app.common.safe_migrations import SafeCreateModel, SafeAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_delete_screenshot'),
    ]

    operations = [
        SafeCreateModel(
            name='RecordingSegment',
            fields=[
                ('id', models.CharField(default=monitoring.models.generate_recording_id, max_length=25, primary_key=True, serialize=False)),
                ('segment_path', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.FloatField()),
                ('segment_index', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_compiled', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_segments', to='monitoring.device')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='monitoring.recording')),
            ],
            options={
                'ordering': ['date', 'segment_index'],
                'indexes': [models.Index(fields=['device', 'date', 'is_compiled'], name='monitoring__device__433838_idx'), models.Index(fields=['date', 'is_compiled'], name='monitoring__date_266bf4_idx')],
            },
        ),
    ]
