# Generated by Django 5.2.1 on 2025-09-27 16:08

from django.db import migrations, models
from app.common.safe_migrations import SafeAlterField


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_seed_activity_types'),
    ]

    operations = [
        SafeAlterField(
            model_name='activitytype',
            name='role_scope',
            field=models.JSONField(blank=True, default=list),
        ),
        SafeAlterField(
            model_name='retentionpolicy',
            name='drop_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        SafeAlterField(
            model_name='retentionpolicy',
            name='role_filter',
            field=models.JSONField(blank=True, default=list),
        ),
        SafeAlterField(
            model_name='retentionpolicy',
            name='target_type_filter',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
