# Generated by Django 5.0.7 on 2025-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0010_add_scheduled_report_and_export_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('CSV', 'Csv'), ('NDJSON', 'Ndjson'), ('PDF', 'Pdf'), ('XML', 'Xml')], max_length=16),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='format',
            field=models.CharField(choices=[('CSV', 'Csv'), ('NDJSON', 'Ndjson'), ('PDF', 'Pdf'), ('XML', 'Xml')], max_length=16),
        ),
    ]
