# Generated by Django 5.2.1 on 2025-09-22 14:20
# Modified to safely handle missing indexes and UUID to integer conversion

from django.db import migrations, models
from app.common.safe_migrations import SafeRenameIndex, SafeAlterField


def convert_uuid_to_integer_if_needed(apps, schema_editor):
    """
    Convert UUID primary keys to integer AutoField if needed.
    Checks current database state before attempting conversion.
    Handles foreign key relationships properly.
    """
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor != 'postgresql':
        # For non-PostgreSQL databases, let Django handle it normally
        return
    
    def get_column_type(cursor, table_name, column_name):
        """Get the data type of a column"""
        cursor.execute("""
            SELECT data_type 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = %s 
            AND column_name = %s
        """, [table_name, column_name])
        result = cursor.fetchone()
        return result[0] if result else None
    
    def table_exists(cursor, table_name):
        """Check if a table exists"""
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            )
        """, [table_name])
        return cursor.fetchone()[0]
    
    def has_data(cursor, table_name):
        """Check if table has any data"""
        try:
            cursor.execute(f'SELECT COUNT(*) FROM {table_name}')
            return cursor.fetchone()[0] > 0
        except Exception:
            return False
    
    with schema_editor.connection.cursor() as cursor:
        # Convert Order.id from UUID to integer
        if table_exists(cursor, 'orders_order'):
            order_id_type = get_column_type(cursor, 'orders_order', 'id')
            if order_id_type == 'uuid':
                cursor.execute("SAVEPOINT sp_convert_order_id")
                try:
                    # Check if there's data
                    has_order_data = has_data(cursor, 'orders_order')
                    
                    if has_order_data:
                        # If data exists, we need to preserve it
                        # Create mapping: UUID -> integer
                        # This is complex, so we'll create a new integer column and populate it
                        cursor.execute("""
                            ALTER TABLE orders_order 
                            ADD COLUMN new_id SERIAL
                        """)
                        
                        # Create sequence starting from 1
                        cursor.execute("""
                            CREATE SEQUENCE IF NOT EXISTS orders_order_new_id_seq;
                            ALTER SEQUENCE orders_order_new_id_seq OWNED BY orders_order.new_id;
                        """)
                        
                        # Populate new_id with sequential integers
                        cursor.execute("""
                            UPDATE orders_order 
                            SET new_id = nextval('orders_order_new_id_seq')
                        """)
                        
                        # Find ALL foreign key constraints that reference orders_order.id
                        # This includes foreign keys from other apps
                        cursor.execute("""
                            SELECT DISTINCT tc.table_name, tc.constraint_name
                            FROM information_schema.table_constraints tc
                            JOIN information_schema.key_column_usage kcu 
                                ON tc.constraint_schema = kcu.constraint_schema
                                AND tc.constraint_name = kcu.constraint_name
                            JOIN information_schema.constraint_column_usage ccu
                                ON ccu.constraint_schema = tc.constraint_schema
                                AND ccu.constraint_name = tc.constraint_name
                            WHERE tc.constraint_type = 'FOREIGN KEY'
                            AND tc.constraint_schema = 'public'
                            AND ccu.table_name = 'orders_order'
                            AND ccu.column_name = 'id'
                        """)
                        all_fk_constraints = cursor.fetchall()
                        
                        # Also get constraints from orders app tables
                        fk_tables = [
                            'orders_orderitem',
                            'orders_quotation',
                            'orders_designstage',
                            'orders_printingstage',
                            'orders_approvalstage',
                            'orders_deliverystage',
                            'orders_upload'
                        ]
                        
                        fk_constraints = []
                        # Add constraints from other apps
                        for fk_table, constraint_name in all_fk_constraints:
                            fk_constraints.append((fk_table, constraint_name))
                        
                        # Also check orders app tables explicitly
                        for fk_table in fk_tables:
                            if table_exists(cursor, fk_table):
                                cursor.execute("""
                                    SELECT constraint_name 
                                    FROM information_schema.table_constraints 
                                    WHERE table_schema = 'public' 
                                    AND table_name = %s 
                                    AND constraint_type = 'FOREIGN KEY'
                                    AND constraint_name LIKE %s
                                """, [fk_table, '%order_id%'])
                                constraints = cursor.fetchall()
                                for constraint in constraints:
                                    if (fk_table, constraint[0]) not in fk_constraints:
                                        fk_constraints.append((fk_table, constraint[0]))
                        
                        # Drop foreign key constraints (use CASCADE if needed)
                        for fk_table, constraint_name in fk_constraints:
                            try:
                                cursor.execute(f'ALTER TABLE {fk_table} DROP CONSTRAINT IF EXISTS {constraint_name} CASCADE')
                            except Exception:
                                try:
                                    cursor.execute(f'ALTER TABLE {fk_table} DROP CONSTRAINT IF EXISTS {constraint_name}')
                                except Exception:
                                    pass
                        
                        # Update foreign keys to use new_id (convert from UUID to integer)
                        for fk_table, _ in fk_constraints:
                            # Check if order_id column exists and is UUID type
                            fk_column_type = get_column_type(cursor, fk_table, 'order_id')
                            if fk_column_type == 'uuid':
                                # Add temporary integer column
                                cursor.execute(f"""
                                    ALTER TABLE {fk_table} 
                                    ADD COLUMN order_id_new integer
                                """)
                                # Populate it with mapped integer values
                                cursor.execute(f"""
                                    UPDATE {fk_table} 
                                    SET order_id_new = (
                                        SELECT o.new_id 
                                        FROM orders_order o 
                                        WHERE o.id::text = {fk_table}.order_id::text
                                    )
                                """)
                                # Check if column is nullable
                                cursor.execute("""
                                    SELECT is_nullable 
                                    FROM information_schema.columns 
                                    WHERE table_schema = 'public' 
                                    AND table_name = %s 
                                    AND column_name = 'order_id'
                                """, [fk_table])
                                is_nullable = cursor.fetchone()[0] == 'YES'
                                
                                # Drop old UUID column
                                cursor.execute(f"ALTER TABLE {fk_table} DROP COLUMN order_id")
                                # Rename new column
                                cursor.execute(f"ALTER TABLE {fk_table} RENAME COLUMN order_id_new TO order_id")
                                # Set NOT NULL only if it wasn't nullable before
                                if not is_nullable:
                                    cursor.execute(f"ALTER TABLE {fk_table} ALTER COLUMN order_id SET NOT NULL")
                        
                        # Drop old UUID column and rename new_id
                        # Use CASCADE to drop dependent objects
                        cursor.execute("ALTER TABLE orders_order DROP CONSTRAINT orders_order_pkey CASCADE")
                        cursor.execute("ALTER TABLE orders_order DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_order RENAME COLUMN new_id TO id")
                        cursor.execute("ALTER TABLE orders_order ADD PRIMARY KEY (id)")
                        
                        # Recreate foreign key constraints
                        # Django will recreate these in subsequent migrations if needed
                    else:
                        # No data, simpler approach: drop and recreate
                        # Drop foreign key constraints first
                        fk_tables = [
                            'orders_orderitem',
                            'orders_quotation',
                            'orders_designstage',
                            'orders_printingstage',
                            'orders_approvalstage',
                            'orders_deliverystage',
                            'orders_upload'
                        ]
                        
                        for fk_table in fk_tables:
                            if table_exists(cursor, fk_table):
                                cursor.execute(f"""
                                    SELECT constraint_name 
                                    FROM information_schema.table_constraints 
                                    WHERE table_schema = 'public' 
                                    AND table_name = %s 
                                    AND constraint_type = 'FOREIGN KEY'
                                    AND constraint_name LIKE %s
                                """, [fk_table, '%order_id%'])
                                constraints = cursor.fetchall()
                                for constraint in constraints:
                                    try:
                                        cursor.execute(f'ALTER TABLE {fk_table} DROP CONSTRAINT IF EXISTS {constraint[0]}')
                                    except Exception:
                                        pass
                        
                        # Drop primary key and UUID column, create integer column
                        # Use CASCADE to handle dependent foreign keys
                        cursor.execute("ALTER TABLE orders_order DROP CONSTRAINT IF EXISTS orders_order_pkey CASCADE")
                        cursor.execute("ALTER TABLE orders_order DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_order ADD COLUMN id SERIAL PRIMARY KEY")
                        
                        # Convert foreign key columns from UUID to integer (no data, so safe to use default)
                        for fk_table in fk_tables:
                            if table_exists(cursor, fk_table):
                                fk_column_type = get_column_type(cursor, fk_table, 'order_id')
                                if fk_column_type == 'uuid':
                                    try:
                                        # Since there's no data, we can just drop and recreate
                                        cursor.execute(f"ALTER TABLE {fk_table} DROP COLUMN order_id")
                                        cursor.execute(f"ALTER TABLE {fk_table} ADD COLUMN order_id integer")
                                    except Exception as e:
                                        print(f"Note: Could not convert {fk_table}.order_id: {e}")
                    
                    cursor.execute("RELEASE SAVEPOINT sp_convert_order_id")
                except Exception as e:
                    cursor.execute("ROLLBACK TO SAVEPOINT sp_convert_order_id")
                    print(f"Note: Could not convert orders_order.id from UUID to integer: {e}")
        
        # Convert OrderItem.id from UUID to integer
        if table_exists(cursor, 'orders_orderitem'):
            orderitem_id_type = get_column_type(cursor, 'orders_orderitem', 'id')
            if orderitem_id_type == 'uuid':
                cursor.execute("SAVEPOINT sp_convert_orderitem_id")
                try:
                    has_orderitem_data = has_data(cursor, 'orders_orderitem')
                    if has_orderitem_data:
                        cursor.execute("ALTER TABLE orders_orderitem ADD COLUMN new_id SERIAL")
                        cursor.execute("""
                            CREATE SEQUENCE IF NOT EXISTS orders_orderitem_new_id_seq;
                            ALTER SEQUENCE orders_orderitem_new_id_seq OWNED BY orders_orderitem.new_id;
                        """)
                        cursor.execute("UPDATE orders_orderitem SET new_id = nextval('orders_orderitem_new_id_seq')")
                        cursor.execute("ALTER TABLE orders_orderitem DROP CONSTRAINT orders_orderitem_pkey")
                        cursor.execute("ALTER TABLE orders_orderitem DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_orderitem RENAME COLUMN new_id TO id")
                        cursor.execute("ALTER TABLE orders_orderitem ADD PRIMARY KEY (id)")
                    else:
                        cursor.execute("ALTER TABLE orders_orderitem DROP CONSTRAINT IF EXISTS orders_orderitem_pkey")
                        cursor.execute("ALTER TABLE orders_orderitem DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_orderitem ADD COLUMN id SERIAL PRIMARY KEY")
                    cursor.execute("RELEASE SAVEPOINT sp_convert_orderitem_id")
                except Exception as e:
                    cursor.execute("ROLLBACK TO SAVEPOINT sp_convert_orderitem_id")
                    print(f"Note: Could not convert orders_orderitem.id from UUID to integer: {e}")
        
        # Convert Upload.id from UUID to integer
        if table_exists(cursor, 'orders_upload'):
            upload_id_type = get_column_type(cursor, 'orders_upload', 'id')
            if upload_id_type == 'uuid':
                cursor.execute("SAVEPOINT sp_convert_upload_id")
                try:
                    has_upload_data = has_data(cursor, 'orders_upload')
                    if has_upload_data:
                        cursor.execute("ALTER TABLE orders_upload ADD COLUMN new_id SERIAL")
                        cursor.execute("""
                            CREATE SEQUENCE IF NOT EXISTS orders_upload_new_id_seq;
                            ALTER SEQUENCE orders_upload_new_id_seq OWNED BY orders_upload.new_id;
                        """)
                        cursor.execute("UPDATE orders_upload SET new_id = nextval('orders_upload_new_id_seq')")
                        cursor.execute("ALTER TABLE orders_upload DROP CONSTRAINT orders_upload_pkey")
                        cursor.execute("ALTER TABLE orders_upload DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_upload RENAME COLUMN new_id TO id")
                        cursor.execute("ALTER TABLE orders_upload ADD PRIMARY KEY (id)")
                    else:
                        cursor.execute("ALTER TABLE orders_upload DROP CONSTRAINT IF EXISTS orders_upload_pkey")
                        cursor.execute("ALTER TABLE orders_upload DROP COLUMN id")
                        cursor.execute("ALTER TABLE orders_upload ADD COLUMN id SERIAL PRIMARY KEY")
                    cursor.execute("RELEASE SAVEPOINT sp_convert_upload_id")
                except Exception as e:
                    cursor.execute("ROLLBACK TO SAVEPOINT sp_convert_upload_id")
                    print(f"Note: Could not convert orders_upload.id from UUID to integer: {e}")


def reverse_convert_uuid_to_integer(apps, schema_editor):
    """
    Reverse operation - convert integer back to UUID (for rollback).
    Note: This is complex and may not preserve data perfectly.
    """
    # This is a complex reverse operation that may not be fully reversible
    # In practice, you'd typically restore from a backup rather than reverse this migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        SafeRenameIndex(
            model_name='order',
            new_name='orders_orde_stage_72c51f_idx',
            old_name='orders_order_stage_status_idx',
        ),
        SafeRenameIndex(
            model_name='order',
            new_name='orders_orde_order_c_cd5b49_idx',
            old_name='orders_order_order_code_idx',
        ),
        SafeRenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_order_created_at_idx',
        ),
        SafeRenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orderitem_order_product_idx',
        ),
        SafeRenameIndex(
            model_name='upload',
            new_name='orders_uplo_order_i_e19425_idx',
            old_name='orders_upload_order_kind_idx',
        ),
        # Convert UUID to integer for id fields
        migrations.RunPython(
            convert_uuid_to_integer_if_needed,
            reverse_convert_uuid_to_integer,
        ),
        # Update order_code default value
        SafeAlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default='TEMP', max_length=20, unique=True),
        ),
        # Update state to reflect integer IDs (Django needs to know the state changed)
        # Use SeparateDatabaseAndState to only update state, not database
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Database already converted by RunPython above
            state_operations=[
                migrations.AlterField(
                    model_name='order',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='orderitem',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='upload',
                    name='id',
                    field=models.AutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
