# Generated by Django 5.2.1
# Modified to safely handle duplicate columns

from django.db import migrations, models
from app.common.safe_migrations import SafeAddField


class Migration(migrations.Migration):

    dependencies = [
        # Depend on 0001_initial which always exists
        # Also depend on 0009 if it exists
        ('orders', '0001_initial'),
        ('orders', '0009_add_trn_and_sales_person_fields'),
    ]

    operations = [
        SafeAddField(
            model_name='orderitem',
            name='design_ready',
            field=models.BooleanField(default=False, help_text='Design status for this product'),
        ),
        SafeAddField(
            model_name='orderitem',
            name='design_need_custom',
            field=models.BooleanField(default=False, help_text='Whether this product needs custom design'),
        ),
        SafeAddField(
            model_name='orderitem',
            name='design_files_manifest',
            field=models.JSONField(default=list, blank=True, help_text='List of design files for this product'),
        ),
    ]

