# Generated by Django 5.2.1 on 2025-10-30 20:07
# UPDATED: Dependencies changed to work on production servers where intermediate migrations may not exist

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # CRITICAL: Depend on 0001_initial (always exists) and 0017 (which depends on 0001)
        # This ensures the merge works on production even if 0014, 0015, 0016, or 0006 don't exist
        # DO NOT change back to depend on 0014 or 0015 - those migrations may not exist on production
        ('orders', '0001_initial'),
        ('orders', '0017_increase_sku_max_length'),
    ]

    operations = [
    ]
