# Generated by Django 5.2.1 on 2025-10-30 20:26

from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models
from app.common.safe_migrations import (
    SafeRemoveIndex, SafeRenameIndex, SafeRemoveField, SafeAddField, SafeAlterField
)


class SafeAlterModelOptions(migrations.AlterModelOptions):
    """AlterModelOptions that safely handles the case where the model doesn't exist in state."""
    
    def state_forwards(self, app_label, state):
        """Override to safely handle missing model in state."""
        # Catch all exceptions - if model doesn't exist or anything goes wrong, skip silently
        try:
            super().state_forwards(app_label, state)
        except Exception:
            # Model doesn't exist in state, skip
            pass


class Migration(migrations.Migration):

    dependencies = [
        # Depend on 0001_initial which always exists
        # The Safe operations will handle missing models/fields gracefully
        ('orders', '0001_initial'),
        ('orders', '0019_add_design_completed_fields_and_fix_productmachine'),
    ]

    operations = [
        SafeAlterModelOptions(
            name='productmachineassignment',
            options={'ordering': ['id']},
        ),
        SafeRemoveIndex(
            model_name='productmachineassignment',
            name='orders_prod_expecte_f7d1e8_idx',
        ),
        SafeRenameIndex(
            model_name='designapproval',
            new_name='orders_desi_sales_p_8226ba_idx',
            old_name='orders_desi_sales_p_1e8c7a_idx',
        ),
        SafeRenameIndex(
            model_name='designapproval',
            new_name='orders_desi_designe_e290c7_idx',
            old_name='orders_desi_designe_b3a7f1_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_order_i_472177_idx',
            old_name='orders_orde_order_i_a1c2d3_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_order_i_6dd9a0_idx',
            old_name='orders_orde_order_i_b2e3f4_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_uploade_5c1872_idx',
            old_name='orders_orde_uploade_c3f4e5_idx',
        ),
        SafeRenameIndex(
            model_name='productmachineassignment',
            new_name='orders_prod_order_i_7d1e95_idx',
            old_name='orders_prod_order_i_d2f3a1_idx',
        ),
        SafeRenameIndex(
            model_name='productmachineassignment',
            new_name='orders_prod_machine_b441cf_idx',
            old_name='orders_prod_machine_e4b2c9_idx',
        ),
        SafeRemoveField(
            model_name='designapproval',
            name='created_at',
        ),
        SafeRemoveField(
            model_name='designapproval',
            name='updated_at',
        ),
        SafeRemoveField(
            model_name='productmachineassignment',
            name='created_at',
        ),
        SafeRemoveField(
            model_name='productmachineassignment',
            name='updated_at',
        ),
        SafeAddField(
            model_name='designstage',
            name='internal_comments',
            field=models.TextField(blank=True, help_text='Internal comments for design stage'),
        ),
        SafeAlterField(
            model_name='designstage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        SafeAlterField(
            model_name='order',
            name='sales_person',
            field=models.CharField(blank=True, help_text='Sales person who sent this order to production', max_length=255, null=True),
        ),
        SafeAlterField(
            model_name='order',
            name='trn',
            field=models.CharField(blank=True, max_length=50),
        ),
        SafeAlterField(
            model_name='orderitem',
            name='design_files_manifest',
            field=models.JSONField(blank=True, default=list, help_text='List of design files for this product - DEPRECATED: Use OrderFile model instead'),
        ),
        SafeAlterField(
            model_name='printingstage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
