# Generated by Django 5.2.1 on 2025-11-17 14:51
# Updated to use SafeAlterField to handle missing model gracefully

from django.db import migrations, models
from app.common.safe_migrations import SafeAlterField


class Migration(migrations.Migration):

    dependencies = [
        # Depend on 0001_initial which always exists
        # Depend on 0024 for the field rename detection fix
        ('orders', '0001_initial'),
        ('orders', '0024_fix_field_rename_detection'),
    ]

    operations = [
        SafeAlterField(
            model_name='productmachineassignment',
            name='product_sku',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
