# Generated by Django 5.2.1 on 2025-11-18 13:29
# Modified to safely handle field renames and removals

from django.db import migrations, models
from app.common.safe_migrations import (
    SafeRenameField, SafeRemoveField, SafeRenameIndex, SafeRemoveIndex, SafeAlterField
)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_fix_field_rename_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmachineassignment',
            options={'ordering': ['id']},
        ),
        SafeRemoveIndex(
            model_name='productmachineassignment',
            name='orders_prod_expecte_f7d1e8_idx',
        ),
        SafeRenameIndex(
            model_name='designapproval',
            new_name='orders_desi_sales_p_8226ba_idx',
            old_name='orders_desi_sales_p_1e8c7a_idx',
        ),
        SafeRenameIndex(
            model_name='designapproval',
            new_name='orders_desi_designe_e290c7_idx',
            old_name='orders_desi_designe_b3a7f1_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_order_i_472177_idx',
            old_name='orders_orde_order_i_a1c2d3_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_order_i_6dd9a0_idx',
            old_name='orders_orde_order_i_b2e3f4_idx',
        ),
        SafeRenameIndex(
            model_name='orderfile',
            new_name='orders_orde_uploade_5c1872_idx',
            old_name='orders_orde_uploade_c3f4e5_idx',
        ),
        SafeRenameIndex(
            model_name='productmachineassignment',
            new_name='orders_prod_order_i_7d1e95_idx',
            old_name='orders_prod_order_i_d2f3a1_idx',
        ),
        SafeRenameIndex(
            model_name='productmachineassignment',
            new_name='orders_prod_machine_b441cf_idx',
            old_name='orders_prod_machine_e4b2c9_idx',
        ),
        SafeRemoveField(
            model_name='designapproval',
            name='created_at',
        ),
        SafeRemoveField(
            model_name='designapproval',
            name='updated_at',
        ),
        SafeRemoveField(
            model_name='productmachineassignment',
            name='created_at',
        ),
        SafeRemoveField(
            model_name='productmachineassignment',
            name='expected_completion_time',
        ),
        # Rename start_time to started_at (instead of remove+add to preserve data)
        SafeRenameField(
            model_name='productmachineassignment',
            old_name='start_time',
            new_name='started_at',
        ),
        SafeRemoveField(
            model_name='productmachineassignment',
            name='updated_at',
        ),
        SafeAlterField(
            model_name='order',
            name='sales_person',
            field=models.CharField(blank=True, help_text='Sales person who sent this order to production', max_length=255, null=True),
        ),
        SafeAlterField(
            model_name='order',
            name='trn',
            field=models.CharField(blank=True, max_length=50),
        ),
        SafeAlterField(
            model_name='orderitem',
            name='design_files_manifest',
            field=models.JSONField(blank=True, default=list, help_text='List of design files for this product - DEPRECATED: Use OrderFile model instead'),
        ),
        SafeAlterField(
            model_name='productmachineassignment',
            name='product_sku',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
