# Generated by Django 5.2.1
# Add channel field to Order model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_productmachineassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(blank=True, choices=[('b2b_customers', 'B2B Customers'), ('b2c_customers', 'B2C Customers'), ('walk_in_orders', 'Walk-In Orders'), ('online_store', 'Online Store (Website / WhatsApp / Instagram / Email)'), ('salesperson_generated', 'Salesperson-Generated Orders')], help_text='Source channel for this order', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['channel'], name='orders_orde_channel_idx'),
        ),
    ]

