# Generated by Django 5.0.7 on 2025-11-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_backfill_profile_tags_from_channel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_channel_491f77_idx',
            old_name='orders_orde_channel_idx',
        ),
    ]
