# Generated by Django 5.0.7 on 2025-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_rename_orders_orde_channel_idx_orders_orde_channel_491f77_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_channel_491f77_idx',
        ),
        # NOTE: RemoveField for 'channel' is a no-op because the field still exists
        # in the database. Migration 0030 added it and it was never actually removed.
        # migrations.RemoveField(
        #     model_name='order',
        #     name='channel',
        # ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
