# Generated by Django 5.0.7 on 2025-11-22 17:10
# NOTE: This migration is a no-op because the 'channel' field was already added
# by migration 0030_add_order_channel_field.py. This migration exists only to
# maintain migration history consistency.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_channel'),
    ]

    operations = [
        # No operations - channel field already exists from migration 0030
        # This migration is kept to maintain history but does nothing
    ]
