# Generated by Django 5.0.7 on 2025-11-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_7088ed_idx',
            old_name='notificatio_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tag_tri_3136a7_idx',
            old_name='notificatio_tag_trig_idx',
        ),
    ]
