# Generated by Django 5.0.7 on 2025-11-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notificatio_user_id_status_idx_notificatio_user_id_7088ed_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
