# Generated by Django 5.0.7 on 2025-11-27 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_tag_trig_idx',
            old_name='notificatio_tag_trig_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_acted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the notification has been read'),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context data for the notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, help_text='ID of the related object', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Type of related object (e.g., order, design_approval, leave_request)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='Short notification title', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('design_submitted', 'Design Submitted'), ('design_approved', 'Design Approved'), ('design_rejected', 'Design Rejected'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('delivery_photo_uploaded', 'Delivery Photo Uploaded'), ('delivery_status_updated', 'Delivery Status Updated'), ('delivery_code_sent', 'Delivery Code Sent'), ('monitoring_device_idle', 'Device Idle'), ('monitoring_pollution_threshold', 'Pollution Threshold Exceeded'), ('monitoring_sensor_offline', 'Sensor Offline')], help_text='Type of notification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='notif_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_object_type', 'related_object_id'], name='notif_rel_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_at_idx'),
        ),
    ]
