# Generated by Django 5.0.7 on 2025-12-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notification_notificatio_user_id_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('order_created', 'Order Created'), ('order_assigned', 'Order Assigned'), ('design_submitted', 'Design Submitted'), ('design_approved', 'Design Approved'), ('design_rejected', 'Design Rejected'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('delivery_photo_uploaded', 'Delivery Photo Uploaded'), ('delivery_status_updated', 'Delivery Status Updated'), ('delivery_code_sent', 'Delivery Code Sent'), ('monitoring_device_idle', 'Device Idle'), ('monitoring_pollution_threshold', 'Pollution Threshold Exceeded'), ('monitoring_sensor_offline', 'Sensor Offline'), ('chat_message_received', 'Chat Message Received'), ('chat_call_incoming', 'Incoming Call'), ('chat_call_missed', 'Missed Call')], help_text='Type of notification', max_length=50, null=True),
        ),
    ]
