# Generated by Django 5.0.7 on 2025-09-18 13:15
# Modified to safely handle existing column

from django.db import migrations, models


class SafeAddField(migrations.AddField):
    """AddField that safely handles the case where the field already exists in the database."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Override to check if field exists before adding."""
        vendor = schema_editor.connection.vendor
        cursor = schema_editor.connection.cursor()
        
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        
        # Get the actual database column name
        # For ForeignKey fields, Django uses field_name + '_id'
        column_name = self.name
        if hasattr(self.field, 'related_model') and self.field.related_model:
            # This is a ForeignKey, check for the _id column
            column_name = f"{self.name}_id"
        
        if vendor == "mysql":
            cursor.execute(
                """
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            exists = cursor.fetchone()[0] > 0
        elif vendor == "sqlite":
            cursor.execute(f'PRAGMA table_info("{table_name}")')
            columns = [row[1] for row in cursor.fetchall()]
            exists = column_name in columns
        else:  # PostgreSQL
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
                """,
                [table_name, column_name],
            )
            exists = cursor.fetchone()[0] > 0
        
        if not exists:
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_device_id"),
    ]

    operations = [
        SafeAddField(
            model_name="attendance",
            name="device_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
