# Generated by Django 5.0.7 on 2025-09-18 14:17
# Modified to safely handle missing unique constraint

from django.db import migrations


class SafeAlterUniqueTogether(migrations.AlterUniqueTogether):
    """AlterUniqueTogether that safely handles the case where the constraint doesn't exist."""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Override to safely handle missing constraint or duplicate indexes."""
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except ValueError as e:
            # If constraint doesn't exist, that's fine - it's already removed
            if "Found wrong number" in str(e) or "constraints" in str(e).lower():
                # Constraint doesn't exist, skip
                return
            # Re-raise other ValueError exceptions
            raise
        except Exception as e:
            # Catch OperationalError for duplicate key/index issues
            error_str = str(e)
            if "Duplicate key" in error_str or "duplicate" in error_str.lower() or "1061" in error_str:
                # Index/constraint already exists or duplicate, skip
                return
            # Re-raise other exceptions
            raise


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_device_name'),
    ]

    operations = [
        SafeAlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
