# Generated by Django 5.2.1 on 2025-11-18 14:29
# Modified to safely handle index renames

from django.db import migrations
from app.common.safe_migrations import SafeRenameIndex


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_leave_request_model'),
    ]

    operations = [
        SafeRenameIndex(
            model_name='leaverequest',
            new_name='attendance__employe_a2f1b5_idx',
            old_name='attendance_leaverequest_employee_status_idx',
        ),
        SafeRenameIndex(
            model_name='leaverequest',
            new_name='attendance__start_d_5c073b_idx',
            old_name='attendance_leaverequest_start_date_end_date_idx',
        ),
        SafeRenameIndex(
            model_name='leaverequest',
            new_name='attendance__status_6e3dfd_idx',
            old_name='attendance_leaverequest_status_idx',
        ),
    ]
